# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import folium
import io
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5 import QtWidgets, QtWebEngineWidgets
import geocoder

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(744, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.iconOnly = QtWidgets.QWidget(self.centralwidget)
        self.iconOnly.setMaximumSize(QtCore.QSize(81, 16777215))
        self.iconOnly.setObjectName("iconOnly")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.iconOnly)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.iconOnly)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.iconOnly)
        self.pushButton.setCheckable(True)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.iconOnly)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setAutoExclusive(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.iconOnly)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setAutoExclusive(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 319, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.pushButton_4 = QtWidgets.QPushButton(self.iconOnly)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.horizontalLayout_4.addWidget(self.iconOnly)
        self.fullMenu = QtWidgets.QWidget(self.centralwidget)
        self.fullMenu.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fullMenu.setObjectName("fullMenu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fullMenu)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.fullMenu)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.fullMenu)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.fullMenu)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setAutoExclusive(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.fullMenu)
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setAutoExclusive(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.fullMenu)
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setAutoExclusive(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 326, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.pushButton_8 = QtWidgets.QPushButton(self.fullMenu)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_4.addWidget(self.pushButton_8)
        self.horizontalLayout_4.addWidget(self.fullMenu)
        self.Content = QtWidgets.QWidget(self.centralwidget)
        self.Content.setObjectName("Content")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Content)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.Content)
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_5.addWidget(self.pushButton_9)
        self.stackedWidget = QtWidgets.QStackedWidget(self.Content)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_5 = QtWidgets.QLabel(self.page)
        #==================================================================================
        m = folium.Map(
        title='coastlines',
        zoom_start=100)

        data = io.BytesIO()
        g = geocoder.ip('me')
        coordinates = g.latlng
        if coordinates is not None:
            latitude, longitude = coordinates
            m = folium.Map(location=[latitude, longitude], zoom_start=100)
        else:
            m = folium.Map(location=[4.7086033306706145, -74.06116161374081], zoom_start=100)


        marker_coord = [[4.706954992957293, -74.06297268202088], [4.707710271226791, -74.05265169756495]]
        marker_coord = []
        marker_radius = 20
        #Mapa
        
        for index, i in enumerate(marker_coord):
            if(index == 0):
                folium.Marker(
                    location = [i[0], i[1]],
                    icon = folium.Icon(color='red'),
                    tooltip='Partida/Llegada',
                    ).add_to(m)
            else:
                folium.vector_layers.Circle(
                location=i,
                tooltip=f"Radio de {marker_radius} metros",
                radius=marker_radius,
                color="red",
                fill=True,
                fill_color="blue"
                    ).add_to(m)
                folium.Marker(
                    location = i,
                    color = 'green',
                    tooltip=f'Estacion #{index}',
                    ).add_to(m)
            #lines
        if(len(marker_coord) > 2):
            folium.PolyLine(
                marker_coord,
                tooltip='Trayectoria de ida',
                color= 'blue',
                weight= 10,
                opacity= 0.5
            ).add_to(m)
            folium.PolyLine(
                [marker_coord[0], marker_coord[-1]],
                tooltip='Trayectoria de regreso',
                color= 'red',
                weight= 10,
                opacity= 0.5
            ).add_to(m)
        elif(len(marker_coord) == 2):
                folium.PolyLine(
                [marker_coord[0], marker_coord[-1]],
                tooltip='Trayectoria de ida y vuelta',
                color= 'purple',
                weight= 10,
                opacity= 0.5
            ).add_to(m)
        m.save(data, close_file=False)
        webView = QtWebEngineWidgets.QWebEngineView()
        webView.setHtml(data.getvalue().decode())

        self.stackedWidget.addWidget(webView)
        

        #==================================================================================
        self.label_5.setGeometry(QtCore.QRect(190, 170, 47, 13))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(150, 130, 47, 13))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(220, 170, 47, 13))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.pushButton.toggled['bool'].connect(self.pushButton_5.setChecked) # type: ignore
        self.pushButton_3.toggled['bool'].connect(self.pushButton_6.setChecked) # type: ignore
        self.pushButton_2.toggled['bool'].connect(self.pushButton_7.setChecked) # type: ignore
        self.pushButton_5.toggled['bool'].connect(self.pushButton.setChecked) # type: ignore
        self.pushButton_6.toggled['bool'].connect(self.pushButton_3.setChecked) # type: ignore
        self.pushButton_7.toggled['bool'].connect(self.pushButton_2.setChecked) # type: ignore
        self.pushButton_9.toggled['bool'].connect(self.fullMenu.setHidden) # type: ignore
        self.pushButton_9.toggled['bool'].connect(self.iconOnly.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "R"))
        self.pushButton_3.setText(_translate("MainWindow", "#"))
        self.pushButton_2.setText(_translate("MainWindow", "M"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.label_3.setText(_translate("MainWindow", "Logo"))
        self.label_2.setText(_translate("MainWindow", "Sidebar"))
        self.pushButton_5.setText(_translate("MainWindow", "Ruta/Mapa"))
        self.pushButton_6.setText(_translate("MainWindow", "3D"))
        self.pushButton_7.setText(_translate("MainWindow", "Metricas"))
        self.pushButton_8.setText(_translate("MainWindow", "Cerrar"))
        self.pushButton_9.setText(_translate("MainWindow", "Menu"))
        self.label_5.setText(_translate("MainWindow", "3d"))
        self.label_4.setText(_translate("MainWindow", "Ruta"))
        self.label_6.setText(_translate("MainWindow", "Metricas"))
